sudo: false
language: node_js
node_js:
- 10.16
jobs:
  include:
  - stage: test
    if: branch != master
      env:
        - NPM_TOKEN=''
    script: yarn run lint && yarn run flow
  - stage: build
    script: yarn run build-sources && yarn add global ./
    if: branch != master
      env:
        - NPM_TOKEN=''
  - stage: deploying
    if: branch = master
    script: yarn build-sources && npm publish || exit 1
